name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      os_selection:
        description: 'Select Target Operating System Matrix'
        type: choice
        required: true
        default: '["ubuntu-latest", "windows-2022", "windows-11-arm", "macos-latest"]'
        options:
          - '["ubuntu-latest", "windows-2022", "windows-11-arm", "macos-latest"]' # All
          - '["ubuntu-latest"]'
          - '["windows-2022"]'
          - '["windows-11-arm"]'
          - '["macos-latest"]'

jobs:

  gfortran:
    name: GFortran (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(github.event.inputs.os_selection || '["ubuntu-latest", "windows-2022", "windows-11-arm", "macos-latest"]') }}


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2.0.2
        if: matrix.os == 'windows-2022' || matrix.os == 'windows-11-arm'
        with:
          environment-name: tf_env
          create-args: python=3.* tensorflow=2.*
          
      - uses: mamba-org/setup-micromamba@v2.0.2
        if: matrix.os != 'windows-2022' && matrix.os != 'windows-11-arm'
        with:
          micromamba-version: '2.0.4-0'
          environment-file: environment.yml
          create-args: >-
            ${{ matrix.os == 'macos-latest' && 'gfortran=14.2.0' || '' }}

      - name: Install GGUF
        shell: bash -e -x -l {0}
        run: |
            git clone https://github.com/ggerganov/llama.cpp
            cd llama.cpp
            git checkout 4e9a7f7f7fb6acbddd1462909c8d696e38edbfcc
            cd gguf-py
            pip install .
            cd ../..

      - name: Build and run
        shell: bash -l {0}
        run: |
            ci/build.sh

  lfortran:
    name: LFortran (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(github.event.inputs.os_selection || '["ubuntu-latest", "windows-2022", "windows-11-arm", "macos-latest"]') }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v2.0.2
        with:
          micromamba-version: '2.0.4-0'
          environment-file: environment.yml
          create-args: >-
            lfortran=0.60.0
            ${{ matrix.os == 'ubuntu-latest' && 'llvm-openmp=11.1.0' || '' }}

      - name: Build and run
        shell: bash -l {0}
        run: |
            ci/build_lfortran.sh
